apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - init-conf.yaml
  - config.yaml
  - services.yaml
  - mongo-statefulset.yaml
  - sa.yaml
secretGenerator:
- name: mongodb-secret
  files:
  - MONGO_INITDB_ROOT_USERNAME=creds/rootUsername.txt
  - MONGO_INITDB_ROOT_PASSWORD=creds/rootPassword.txt
  - MONGODB_USERNAME=creds/username.txt
  - MONGODB_PASSWORD=creds/password.txt
  - MONGODB_USERS_LIST=creds/userlist.txt
- name: mongodb-keyfile
  files:
  - mongodb.key=./mongodb.key
